server:
  port: 8081

#Spring Cloud Gateway to automatically fetch all routes to api-gateway
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true


#      routes:
#      - id: auth-service
#        uri: lb://auth-service
#        predicates:
#          - Path=/auth-service/**
#      - id: customer-service
#        uri: lb://customer-service
#        predicates:
#          - Path=/customer-service/**
#        filters:
#          - AuthenticationFilter
#      - id: configserver
#        uri: lb://configserver
#        predicates:
#          - Path=/configserver/**
#      - id: payment-service
#        uri: lb://payment-service
#        predicates:
#          - Path=/payment-service/**
#      - id: shopping-cart-service
#        uri: lb://shopping-cart-service
#        predicates:
#          - Path=/shopping-cart-service/**



