global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'service-discovery'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['service-discovery:8761']

  - job_name: 'cloud-config'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cloud-config:8071']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8081']

  - job_name: 'auth-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-server:8083']

  - job_name: 'catalog-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['catalog-service:8084']

  - job_name: 'customer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['customer-service:8082']

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8085']

  - job_name: 'shopping-cart-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['shopping-cart-service:8086']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8087']

  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory-service:8088']

  - job_name: 'coupon-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['coupon-service:8089']

  - job_name: 'review-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['review-service:8090']

  - job_name: 'wishlist-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['wishlist-service:8091']

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8092']
